device: "cuda"  # cpu/ cuda
model:
  name: "bnet"
  save_path: "params/"  # weight saving path
save_image_path: "saved_images"  # save the predicted pic

# 数据加载器配置
data_loader:
  batch_size: 8
  shuffle: true
  num_workers: 16

# 数据集公共配置
datasets:
  isic2018:
    size: 256
    class_num: 1
    dataset_path: "LoadData"
    img_prefix: "ISIC_"
    seg_prefix: "ISIC_"
    img_suffix: ".jpg"
    seg_suffix: "_segmentation.png"
    img: "isic2018/test/img"
    mask: "isic2018/test/mask"
    "augmentations": [
      { "type": "RandomHorizontalFlip", "p": 0.5 },
      { "type": "RandomRotation", "degrees": 30 },
      { "type": "Resize", "size": [ 128, 128 ] },
      {
        "type": "ColorJitter",
        "brightness": [ 0.8, 1.5 ],
        "contrast": 0.2,
        "saturation": 0.3,
        "hue": 0.05
      }


# 测试配置
test_setting:
  seed: 1234
  dataset_name: "isic2018"
