device: "cuda"  # cpu/ cuda
model_name: "bnet"
save_image_path: "saved_images"  # save the predicted pic
model_path: "params/"  # weight saving path

# data loader
batch_size: 8
shuffle: true  # shuffle the data
num_workers: 16

# training setting
train_setting:
  lr: 0.001
  eta_min: 0.00001

  t_max: 25
  epochs: 100  # epoch size
  warmup_epochs: 10

  save_interval: 50  # 多少步（batches）保存一次模型权重
  train_dataset_name: "isic2018" #choose train dataset

  train_dataset:
    isic2018: # choose the isic data set
      size: 256
      class_num: 1
      dataset_path: "LoadData"
      # must be absolute path from system root
      train_data_mask: "isic2018/train/mask"
      train_data_img: "isic2018/train/img"

      img_prefix: "ISIC_"
      seg_prefix: "ISIC_"
      img_suffix: ".jpg"
      seg_suffix: "_segmentation.png"

test_setting:
  seed: 1234
  test_dataset_name: "isic2018"
  test_dataset:
    isic2018:
      class_num: 1
      size: 256
      dataset_path: "LoadData"
      train_data_mask: "isic2018/test/mask"
      train_data_img: "isic2018/test/img"

      img_prefix: "ISIC_"
      seg_prefix: "ISIC_"
      img_suffix: ".jpg"
      seg_suffix: "_segmentation.png"

# 输出图像和模型路径
