device: "cuda"  # cpu/ cuda
model:
  save_path: "params/"  # weight saving path

# 保存训练结果
save_pic: False
save_image_path: "saved_images"  # save the predicted pic

# 数据加载器配置
data_loader:
  batch_size: 16
  shuffle: true
  num_workers: 16

# 训练配置
setting:
  epochs: 100

  max_lr: 0.001
  power: 0.9
  min_lr: 0.00001
  warmup_epochs: 10


# 数据集公共配置
# 由于不同数据可能会使用不同的增强方式
# 所以将增强的定义放在这里管理
datasets:
  isic2018:
    size: 224
    class_num: 1
    in_channel: 3
    dataset_path: "LoadData"
    img_prefix: "ISIC_"
    seg_prefix: "ISIC_"
    img_suffix: ".jpg"
    seg_suffix: "_segmentation.png"
    
    train_img: "isic2018/train/img"
    train_mask: "isic2018/train/mask"

    val: True
    val_img: "isic2018/val/img"
    val_mask: "isic2018/val/mask"

    test_img: "isic2018/test/img"
    test_mask: "isic2018/test/mask"

    augmentations: {
      "geometric_transforms": [
        { "type": "Resize", "params": { "size": [224, 224] } }
      ],
      "color_transforms": [
      ]
    }
  kvasir:
    size: 224
    class_num: 1
    in_channel: 3
    dataset_path: "LoadData"
    img: "Kvasir-SEG/images"
    mask: "Kvasir-SEG/masks"
    augmentations: {
      "geometric_transforms": [
        { "type": "Resize", "params": { "size": [ 224, 224 ] } }
      ],
      "color_transforms": [
      ]
    }
  clinicdb:
    size: 224
    class_num: 1
    in_channel: 3
    dataset_path: "LoadData"
    img: "CVC-ClinicDB/Original"
    mask: "CVC-ClinicDB/Ground Truth"
    augmentations: {
      "geometric_transforms": [
        { "type": "Resize", "params": { "size": [ 224, 224 ] } }
      ],
      "color_transforms": [
      ]
    }
  synapse:
    size: 224
    class_num: 9
    in_channel: 1
    root_path: "LoadData/Synapse/train_npz"
    list_dir: "LoadData/Synapse/lists_Synapse"

    augmentations: {
      "geometric_transforms": [
        { "type": "Resize", "params": { "size": [ 224, 224 ] } }
      ],
      "color_transforms": [
      ]
    }
