device: "cuda"  # cpu/ cuda
model:
  name: "bnet"
  save_path: "params/"  # weight saving path

# 保存训练结果
save_pic: False
save_image_path: "saved_images"  # save the predicted pic

# 数据加载器配置
data_loader:
  batch_size: 16
  shuffle: true
  num_workers: 16

# 测试配置
setting:
  seed: 42
  dataset_name: "clinicdb"
  epochs: 100


# 数据集公共配置
datasets:
  clinicdb:
    size: 224
    class_num: 1
    in_channel: 3
    dataset_path: "LoadData"
    img: "CVC-ClinicDB/Original"
    mask: "CVC-ClinicDB/Ground Truth"
    augmentations: {
      "geometric_transforms": [
        { "type": "Resize", "params": { "size": [ 224, 224 ] } }
      ],
      "color_transforms": [
      ]
    }
