device: "cuda"  # cpu/ cuda
model:
  name: "bnet"
  save_path: "params/"  # weight saving path

save_pic: True
save_image_path: "saved_images"  # save the predicted pic

# 数据加载器配置
data_loader:
  batch_size: 8
  shuffle: true
  num_workers: 16

# 训练配置
train_setting:
  dataset_name: "isic2018"
  epochs: 100
  save_interval: 50
  lr: 0.001
  eta_min: 0.00001
  t_max: 25
  warmup_epochs: 10


# 数据集公共配置
# 由于不同数据可能会使用不同的增强方式
# 所以将增强的定义放在这里管理
datasets:
  isic2018:
    size: 256
    class_num: 1
    dataset_path: "LoadData"
    img_prefix: "ISIC_"
    seg_prefix: "ISIC_"
    img_suffix: ".jpg"
    seg_suffix: "_segmentation.png"
    img: "isic2018/train/img"
    mask: "isic2018/train/mask"
    augmentations: {
      "geometric_transforms": [
        { "type": "RandomHorizontalFlip", "params": { "p": 0.5 } },
        { "type": "RandomRotation", "params": { "degree": 30 } },
        { "type": "Resize", "params": { "size": [256, 256] } }
      ],
      "color_transforms": [
      ]
    }
  kvasir:
    size: 256
    class_num: 1
    dataset_path: "LoadData"
    img_suffix: ".jpg"
    seg_suffix: ".jpg"
    img: "Kvasir-SEG/images"
    mask: "Kvasir-SEG/masks"
    augmentations: {
      "geometric_transforms": [
        { "type": "Resize", "params": { "size": [ 256, 256 ] } }
      ],
      "color_transforms": [
      ]
    }

  DRIVE:
    size: 256
    class_num: 1
    dataset_path: "LoadData"
    img_prefix: "ISIC_"
    seg_prefix: "ISIC_"
    img_suffix: ".jpg"
    seg_suffix: "_segmentation.png"
    img: "isic2018/train/img"
    mask: "isic2018/train/mask"
