device: "cuda"  # cpu/ cuda
model:
  name: "unet"
  save_path: "params/"  # weight saving path

# 保存训练结果
save_pic: False
save_image_path: "saved_images"  # save the predicted pic

# 数据加载器配置
data_loader:
  batch_size: 16
  shuffle: true
  num_workers: 16

# 训练配置
setting:
  dataset_name: "synapse"
  epochs: 100

  lr: 0.0001
  power: 0.9
  eta_min: 0.000001
  warmup_epochs: 10


# 数据集公共配置
# 由于不同数据可能会使用不同的增强方式
# 所以将增强的定义放在这里管理
datasets:
  isic2018:
    size: 256
    class_num: 1
    dataset_path: "LoadData"
    img_prefix: "ISIC_"
    seg_prefix: "ISIC_"
    img_suffix: ".jpg"
    seg_suffix: "_segmentation.png"
    img: "isic2018/train/img"
    mask: "isic2018/train/mask"
    augmentations: {
      "geometric_transforms": [
        { "type": "RandomHorizontalFlip", "params": { "p": 0.5 } },
        { "type": "RandomRotation", "params": { "degree": 15 } },
        { "type": "Resize", "params": { "size": [256, 256] } }
      ],
      "color_transforms": [
      ]
    }
  kvasir:
    size: 256
    class_num: 1
    dataset_path: "LoadData"
    img: "Kvasir-SEG/images"
    mask: "Kvasir-SEG/masks"
    augmentations: {
      "geometric_transforms": [
        { "type": "RandomHorizontalFlip", "params": { "p": 0.5 } },
        { "type": "RandomRotation", "params": { "degree": 15 } },
        { "type": "Resize", "params": { "size": [ 256, 256 ] } }
      ],
      "color_transforms": [
      ]
    }
  clinicdb:
    size: 256
    class_num: 1
    dataset_path: "LoadData"
    img: "CVC-ClinicDB/Original"
    mask: "CVC-ClinicDB/Ground Truth"
    augmentations: {
      "geometric_transforms": [
        { "type": "RandomHorizontalFlip", "params": { "p": 0.5 } },
        { "type": "RandomRotation", "params": { "degree": 15 } },
        { "type": "Resize", "params": { "size": [ 256, 256 ] } }
      ],
      "color_transforms": [
      ]
    }
  synapse:
    size: 224
    class_num: 9
    dataset_path: "LoadData"
    img: "Synapse/all/images"
    mask: "Synapse/all/masks_rgb"
    augmentations: {
      "geometric_transforms": [
        { "type": "Resize", "params": { "size": [ 224, 224 ] } }
      ],
      "color_transforms": [
      ]
    }
